### ISSUE TITLE
PIS 'disease' doesn't work with Apache Jena (RIOT) v4.5.0

### ISSUE THREAD

**Issue by mbdebian** [opentargets/issues#2599]
## Describe the bug
When running riot from Apache Jena v4.5.0, it produces a different output compared to v4.4.0, which makes PIS crash at _disease_ step, after trying to process _EFO_ data.

## Observed behaviour
This error is preventing PIS from completing _disease_ step:
```
2022-05-23 12:16:12,950 plugins.helpers.EFO ERROR - Error processing child: {"@id": "obo:GO_0051641"}
ERROR: 'dict' object has no attribute 'startswith'
```

Detected within this code block in the _EFO Helper_ module of PIS
```python
def get_nodes(self, node, path):
        """
        Compute all the location ID children under a given node recursively in the node subtree.

        :param node: node to get the children for
        :param path: already visited nodes
        :return: all the location ID children for the given node, taking into account the already visited nodes
        """
        logger.debug("[EFO Helper]\t\t\t---| Get nodes |---")
        data = set()
        data.add(node)
        path.add(node)
        children = self.get_children(node)
        if children:
            lista = set()
            for child in children:
                try:
                    if not child.startswith("obo:"):
                        lista.update(self.get_nodes(child, path))
                    else:
                        child_clean_code = re.sub(r'^.*?:', '', child)
                        lista.add(child_clean_code)
                except Exception as e:
                    logger.error("Error processing child: {}\nERROR: {}".format(json.dumps(child), e))
            data.update(lista)
        return data
```

It looks like when using Apache Jena v4.4.0, the child node is just a string, while in Jena v4.5.0 conversion output, it is an object with one key, _@id_

## Expected behaviour
All child nodes within the EFO converted dataset should be processed

## To Reproduce
Steps to reproduce the behaviour:
1. Build a _docker_ image for PIS using the provided _Dockerfile_
2. Run _disease_ step as directed by the instructions on the README file

**Additional context**
Although we could freeze Apache Jena to version 4.4.0, this is not easy when it comes to development environments that don't use the containerization process for debugging while carrying out development tasks in PIS, and we need to find out why there is such a big change in Apache Jena output from _String_ to _Object (dict)_ when using the latest version, as this could unveil inconsistencies in its output for previous releases.

**Comment by mbdebian** [comment]
This issue is very likely to be related to structural changes in the conversion output, thus, I downloaded EFO v3.42.0 from [here](https://github.com/EBISPOT/efo/releases/download/v3.42.0/efo_otar_slim.owl), and run a RIOT conversion to JSON-LD, with the following results:

Given a sample **ID** _efo:EFO_0007516_

For **RIOT v4.4.0**
```json
{
  "@id": "efo:EFO_0007516",
  "@type": "Class",
  "IAO_0000115": [
    "A parasitic helminthiasis infectious disease that involves zoonotic infection of humans by the larvae of Toxocara canis or Toxocara cati. The larvae invade multiple tissues like liver, heart, lungs, brain, muscle and eyes causing various symptoms including fever, anorexia, weight loss, cough, wheezing, rashes, hepatosplenomegaly, hypereosinophilia and ophthalmologic lesions.",
    "A parasitic infection caused by worms found in domestic animals. In humans nematode larvae enter the portal system from the small intestine and disseminate in visceral organs causing inflammatory reactions. Signs and symptoms include eosinophilia, hepatomegaly, splenomegaly, and lung infections."
  ],
  "IAO_0000117": "Sirarat Sarntivijai",
  "closeMatch": "http://identifiers.org/meddra/10044269",
  "exactMatch": [
    "obo:Orphanet_3343",
    "http://identifiers.org/snomedct/406619001",
    "obo:NCIT_C34758",
    "http://linkedlifedata.com/resource/umls/id/C0040553",
    "obo:DOID_9790",
    "http://identifiers.org/mesh/D014120"
  ],
  "hasDbXref": [
    "MedDRA:10044269",
    "MONDO:0005988",
    "ICD9:128.0",
    "Orphanet:3343",
    "MESH:D014120",
    "NCIT:C34758",
    "DOID:9790",
    "MeSH:D007816",
    "SCTID:406619001",
    "GARD:0007788",
    "UMLS:C0040553"
  ],
  "hasExactSynonym": [
    "toxocariasis",
    "Larva Migrans, Visceral",
    "visceral larva migrans",
    "Toxocara infectious disease",
    "Toxocara infection",
    "Toxocara disease or disorder",
    "infection by Toxascaris",
    "Infection by Toxascaris (disorder)",
    "Toxocara caused disease or disorder"
  ],
  "id": "EFO:0007516",
  "inSubset": "mondo:ordo_disease",
  "label": "toxocariasis",
  "subClassOf": "efo:EFO_0007156"
}
```

For **RIOT v4.5.0**
```json
{
  "@id": "efo:EFO_0007516",
  "obo:IAO_0000117": "Sirarat Sarntivijai",
  "obo:IAO_0000115": [
    "A parasitic helminthiasis infectious disease that involves zoonotic infection of humans by the larvae of Toxocara canis or Toxocara cati. The larvae invade multiple tissues like liver, heart, lungs, brain, muscle and eyes causing various symptoms including fever, anorexia, weight loss, cough, wheezing, rashes, hepatosplenomegaly, hypereosinophilia and ophthalmologic lesions.",
    "A parasitic infection caused by worms found in domestic animals. In humans nematode larvae enter the portal system from the small intestine and disseminate in visceral organs causing inflammatory reactions. Signs and symptoms include eosinophilia, hepatomegaly, splenomegaly, and lung infections."
  ],
  "oboInOwl:hasExactSynonym": [
    "toxocariasis",
    "Larva Migrans, Visceral",
    "visceral larva migrans",
    "Toxocara infectious disease",
    "Toxocara infection",
    "Toxocara disease or disorder",
    "infection by Toxascaris",
    "Infection by Toxascaris (disorder)",
    "Toxocara caused disease or disorder"
  ],
  "mondo:exactMatch": [
    {
      "@id": "obo:Orphanet_3343"
    },
    {
      "@id": "http://identifiers.org/snomedct/406619001"
    },
    {
      "@id": "obo:NCIT_C34758"
    },
    {
      "@id": "http://linkedlifedata.com/resource/umls/id/C0040553"
    },
    {
      "@id": "obo:DOID_9790"
    },
    {
      "@id": "http://identifiers.org/mesh/D014120"
    }
  ],
  "oboInOwl:id": "EFO:0007516",
  "oboInOwl:hasDbXref": [
    "MedDRA:10044269",
    "MONDO:0005988",
    "ICD9:128.0",
    "Orphanet:3343",
    "MESH:D014120",
    "NCIT:C34758",
    "DOID:9790",
    "MeSH:D007816",
    "SCTID:406619001",
    "GARD:0007788",
    "UMLS:C0040553"
  ],
  "rdfs:label": "toxocariasis",
  "oboInOwl:inSubset": {
    "@id": "mondo:ordo_disease"
  },
  "mondo:closeMatch": {
    "@id": "http://identifiers.org/meddra/10044269"
  },
  "rdfs:subClassOf": {
    "@id": "efo:EFO_0007156"
  },
  "@type": "Class"
}
```

@DSuveges @d0choa, I think this would benefit from a chat together to find out why Apache Jena seems to be populating namespaces into output keys, and changing some attribute values from primitive types to objects.

**Comment by mbdebian** [comment]
This is not going to change, PIS will run via either a docker image (custom RIOT install) or an operations VM (again, custom environment).

We don't need to review the new RIOT version output right now.
